'''
Created on 29-Sep-2024

@author: admin
'''
print(1+2)
print(3*5)
try:
    print(6/0)
except Exception as e:
    print(e)
finally:
    print("Finally block")    
print(9^2)
    